# Generated by Django 3.2.3 on 2021-05-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210522_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_otp',
            field=models.PositiveIntegerField(default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_otp',
            field=models.PositiveIntegerField(default=1, max_length=6),
        ),
    ]
