# Generated by Django 3.2.3 on 2021-05-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210522_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email_otp',
        ),
    ]
