# Generated by Django 3.2.3 on 2021-05-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_customer_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_otp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_otp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
