# Generated by Django 3.2.3 on 2021-05-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210522_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_otp',
        ),
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
