# Generated by Django 3.2.3 on 2021-05-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_customer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
